version: '3'

services:
  product_details:
    build: ./product_details
    volumes:
      - .:/product_details

  product_list:
    build: ./product_list
    volumes:
      - .:/product_list

  db:
    image: postgres
    container_name: storeDB
    restart: unless-stopped
    volumes:
      - ./data/db/:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
