version: '3'

services:
  product_details:
    build: ./product_details
    volumes:
      - .:/product_details
    ports:
      - 8080:8001

  product_list:
    build: ./product_list
    volumes:
      - .:/product_list
    ports:
      - 8081:8001

  db:
    image: postgres
    container_name: productsdb
    restart: unless-stopped
    volumes:
      - ./data/db/:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  pgadminprod:
    image: dpage/pgadmin4
    container_name: dbadmin
    depends_on:
      - db
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5051:80"
